### ISSUE TITLE
Failure to import on Python 3.6 due to cf-xarray

### ISSUE THREAD

**Issue by zmoon** [pangeo-data/xESMF#189]
I don't mean to suggest that people should still be using Python 3.6, but I noticed this issue in https://github.com/noaa-oar-arl/monet/pull/114.

Basically, up until and including v0.7.2, cf-xarray still purported to support Python 3.6, but they started using `from __future__ import annotations` in v0.7.0. So on Python 3.6, cf-xarray v0.7.2 gets installed for xESMF and then `xesmf` fails to import due to `cf_xarray` failing to import.

**Comment by aulemahal** [comment]
For python and numpy dependencies, `xESMF` follows the rest of the "xarray" ecosystem ([xarray](https://docs.xarray.dev/en/stable/getting-started-guide/installing.html#minimum-dependency-versions), [numpy](https://numpy.org/neps/nep-0029-deprecation_policy.html) ). So using python 3.6 and python 3.7 with latest versions is indeed risky.

However, we haven't update the minimum versions, so it should be feasible to use python 3.6 with cf_xarray < 0.7.2. 
Do I understand that this is rather a bug from  `cf_xarray`? Maybe the minimum python version should have been pinned in 0.7.2? I see that this has been fixed in the latest release.

I guess a solution would be to remove 0.7.2 from the conda archive?  @dcherian ?

**Comment by zmoon** [comment]
> Do I understand that this is rather a bug from `cf_xarray`?

Yes, from my brief investigation it looks like they should have set minimum Python to 3.7 for their v0.7.0 release.

**Comment by zmoon** [comment]
> I guess a solution would be to remove 0.7.2 from the conda archive?

Note that 0.7.0 is affected as well and they are noarch builds, so can't just remove py36 ones.

**Comment by dcherian** [comment]
Ooops what should I do?

**Comment by zmoon** [comment]
Perhaps removing 0.7.2 and 0.7.0 from conda-forge archive as was suggested could be a good partial solution.

**Comment by huard** [comment]
@aulemahal Ok to close this and let cf-xarray devs deal with this ?

**Comment by huard** [comment]
Will close this as there is no obvious action to take on our end. Let us know if I misunderstood.
