### ISSUE TITLE
Release 0.4.0 to pypi

### ISSUE THREAD

**Issue by lukasbindreiter** [pangeo-data/xESMF#46]
Hi,

It seems that this package has suceeded https://github.com/JiaweiZhuang/xESMF as development for `xesmf`. 

I was trying out some of the new features of v0.4, but I noticed that this version is not yet pushed to [PyPI](https://pypi.org/project/xesmf/). Also it seems that the PyPI package still links to the old repository as well.

Would it be possible to update the package (and maybe also the links)

Thanks.

**Comment by huard** [comment]
The original developer is inactive, so we cannot upload new releases to PyPI under the `xesmf` name. One option would be to create a new PyPI entry named `pangeo-xesmf`.

**Comment by huard** [comment]
@ocefpaf I see that everything is ready to go in the github action. Could you set-it up to use the `pangeo-xesmf` name or do we need something else ?

**Comment by ocefpaf** [comment]
Sure, we can do that. But I don't recommend it because:
 - it can be very confusing;
 - you'll need to implement a "PyPI name", [see here for an example](https://github.com/SciTools/iris/blob/master/setup.py#L14);
 - `xESMF` is not really pip-installable, I believe that most of the people install it via vonda. so we GitHub would suffice.

Also, as a long term plan you can try: https://www.python.org/dev/peps/pep-0541/#continued-maintenance-of-an-abandoned-project

PS: do you need help with the GitHub release? If you are willing to give me access to the repo I can handle that for you.

**Comment by huard** [comment]
The current situation is not much better, where the PyPI xesmf points to the old repo, hence this initiative. But if it is not pip- installable, I agree it doesn't make much sense, and we should focus on the conda install. 

Yes, that was the original idea, but it's going to be a while before we meet the requirements to change the PyPi owner. 

Yes, that would be swell ! Done !

**Comment by huard** [comment]
0.4 is now on Conda. 

@lukasbindreiter I'm afraid this is the best we can do at the moment. 

Thanks @ocefpaf !

**Comment by lukasbindreiter** [comment]
Thanks for your efforts.

I didn't know @JiaweiZhuang was inactive, maybe he will come back one day and is able to transfer ownership then.

Thanks for updating the version on conda 👍 

For everyone who uses `pip` or `pipenv` these are the commands I used to install `v0.4.0`:

```
pip install git+https://github.com/pangeo-data/xesmf.git@v0.4.0
```

or

```
pipenv install "git+https://github.com/pangeo-data/xesmf.git@v0.4.0#egg=xesmf"
```

**Comment by lukasbindreiter** [comment]
@huard I think you are the person who would know this, could you quickly come back to us regarding the above question?
