### ISSUE TITLE
Lat/lon inference fails with rlat/rlon

### ISSUE THREAD

**Issue by aulemahal** [pangeo-data/xESMF#55]
With #49 we have what we could call a regression for datasets with `rlat` and `rlon` coordinates (and maybe other cases): those are seen by `cf_xarray` as "longitude" and "latitude". Thus, the following fails with `ValueError` : 
https://github.com/pangeo-data/xESMF/blob/fb739ab920baa822838729d95100243e775a1c7b/xesmf/frontend.py#L39

A workaround would be to catch the ValueError and revert to old-behaviour : `lon = ds['lon']`.
But maybe there is a better way to deal with this problem? We can get all longitude coords with `ds.cf[['longitude']]`, but how do we know which one to use?

**Comment by jthielen** [comment]
If I'm interpreting this correctly, I *think* `rlat` and `rlon` coordinates as grid latitudes/longitudes rather than true latitudes/longitudes should not be identified as latitude/longitude in the context of the CF conventions, so shouldn't be seen by cf_xarray as latitude/longitude (meaning this would need to be fixed upstream). Does that seem reasonable?

**Comment by aulemahal** [comment]
That makes sense. In my specific case, `rlon` had the 'grid_longitude' standard name and this is what caused `cf-xarray` to detect it as a 'longitude'.

**Comment by jthielen** [comment]
> That makes sense. In my specific case, `rlon` had the 'grid_longitude' standard name and this is what caused `cf-xarray` to detect it as a 'longitude'.

Got it. In that case, I definitely think cf-xarray is in error here (as described in http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#rotated-pole-grid-ex, the standard name of `grid_longitude` and units of `degrees` should make it so that these are not confused with true latitudes and longitudes).

**Comment by dcherian** [comment]
> the standard name of grid_longitude and units of degrees should make it so that these are not confused with true latitudes and longitudes).

Ooops my bad. I made that change recently without looking in to it too much. Happy to merge a cf-xarray PR quickly if one of you wants to send one in.

**Comment by aulemahal** [comment]
Closing as this is unrelated to xESMF and will be fixed upstream.
